import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Inter,
  Onest,
  Passion_One,
  Paytone_One,
} from "next/font/google";
import { Layout } from "../components/layout/Layout";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});

const passionOne = Passion_One({
  variable: "--font-passion-one",
  subsets: ["latin"],
  weight: "400",
});

const paytoneOne = Paytone_One({
  variable: "--font-paytone-one",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-gray-100">
      <body
        className={`${passionOne.variable} ${paytoneOne.variable} ${onest.variable} ${inter.variable} ${geistSans.variable} ${geistMono.variable} antialiased h-full bg-gray-100`}
      >
        <Layout title="Hello">{children}</Layout>
      </body>
    </html>
  );
}
